### ISSUE TITLE
Possible Timing Error

### ISSUE THREAD

**Issue by Venom1987** [ketho-wow/KethoInstanceTimer#1]
I think i encounterd a wierd "error"?

I was soloing a older raid and went straight from within that raid into a random heroic dungeon. At the end of the dungeon the timer that posts in the chat said something in the ballpark of 41 minutes, even if that could never be the case since i usually rush throu such dungeons within around 15 - 18 minutes.

**Comment by Ketho** [comment]
Yea that is a bug, can you try the v3.0.3 release
https://www.curseforge.com/wow/addons/kethoinstancetimer/files/2880144
