### ISSUE TITLE
A lot of errors [Retail 10.0.2]

### ISSUE THREAD

**Issue by Hollicsh** [ketho-wow/KethoInstanceTimer#3]
1x ...aceKethoInstanceTimer/KethoInstanceTimer.lua:5: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "LibSink-2.0".
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:185: in function `EmbedLibrary'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:167: in function `EmbedLibraries'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:134: in function `NewAddon'
[string "@KethoInstanceTimer/KethoInstanceTimer.lua"]:5: in main chunk

Locals:
(*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "LibSink-2.0"."

---
---
---

1x KethoInstanceTimer/Options.lua:9: attempt to index local 'KIT' (a nil value)
[string "@KethoInstanceTimer/Options.lua"]:9: in main chunk

Locals:
NAME = "KethoInstanceTimer"
S = <table> {
 L = <table> {
 }
 BUILD = "Release"
 VERSION = "v3.1.3"
}
KIT = nil
ACD = <table> {
 ConfigTableChanged = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1816
 CloseAll = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1797
 Close = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1807
 SetDefaultSize = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1827
 tooltip = AceConfigDialogTooltip {
 }
 Open = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1842
 AddToBlizOptions = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1974
 BlizOptions = <table> {
 }
 popup = Frame {
 }
 GetStatusTable = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:401
 OpenFrames = <table> {
 }
 Status = <table> {
 }
 frame = Frame {
 }
 FeedGroup = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1587
 SelectGroup = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:431
}
L = <table> {
}
profile = nil
char = nil
(*temporary) = <function> defined @KethoInstanceTimer/Options.lua:9
(*temporary) = 86
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'KIT' (a nil value)"

---
---
---

1x KethoInstanceTimer/Core.lua:16: attempt to index local 'KIT' (a nil value)
[string "@KethoInstanceTimer/Core.lua"]:16: in main chunk

Locals:
NAME = "KethoInstanceTimer"
S = <table> {
 L = <table> {
 }
 BUILD = "Release"
 VERSION = "v3.1.3"
}
KIT = nil
ACR = <table> {
 RegisterOptionsTable = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:316
 validated = <table> {
 }
 tables = <table> {
 }
 callbacks = <table> {
 }
 RegisterCallback = <function> defined @ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:88
 GetOptionsTable = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:361
 UnregisterCallback = <function> defined @ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:151
 IterateOptionsTables = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:347
 NotifyChange = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:290
 ValidateOptionsTable = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:277
 UnregisterAllCallbacks = <function> defined @ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:172
}
ACD = <table> {
 ConfigTableChanged = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1816
 CloseAll = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1797
 Close = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1807
 SetDefaultSize = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1827
 tooltip = AceConfigDialogTooltip {
 }
 Open = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1842
 AddToBlizOptions = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1974
 BlizOptions = <table> {
 }
 popup = Frame {
 }
 GetStatusTable = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:401
 OpenFrames = <table> {
 }
 Status = <table> {
 }
 frame = Frame {
 }
 FeedGroup = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1587
 SelectGroup = <function> defined @AddOnSkins/Libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:431
}
L = <table> {
}
options = nil
profile = nil
char = nil
(*temporary) = <function> defined @KethoInstanceTimer/Core.lua:16
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'KIT' (a nil value)"

---
---
---

1x KethoInstanceTimer/KethoInstanceTimer.lua:1 (null)

---
---
---

1x KethoInstanceTimer/Options.lua:1 (null)

---
---
---

1x KethoInstanceTimer/Core.lua:1 (null)

---
---
---

1x Interface\FrameXML\Bindings.xml:1 KethoInstanceTimer/KethoInstanceTimer.lua:1 (null)

---
---
---

1x Interface\FrameXML\Bindings.xml:1 KethoInstanceTimer/Options.lua:1 (null)

---
---
---

1x Interface\FrameXML\Bindings.xml:1 KethoInstanceTimer/Core.lua:1 (null)

---
---
---

196x KethoInstanceTimer/Broker.lua:51: attempt to index field 'pvp' (a nil value)
[string "@KethoInstanceTimer/Broker.lua"]:51: in function <KethoInstanceTimer/Broker.lua:50>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'pvp' (a nil value)"
S = <table> {
 L = <table> {
 }
 BUILD = "Release"
 VERSION = "v3.1.3"
}
GetBattlefieldInstanceRunTime = <function> defined =[C]:-1
dataobject = <table> {
}
MilitaryTime = <function> defined @KethoInstanceTimer/Broker.lua:34
KIT = nil

---
---

Problem with ElvUI ?

**Comment by Ketho** [comment]
I made a dummy mistake, commented out the libs in my working copy and forgot to undo 😅
