### ISSUE TITLE
Issue in patch 11.0.2

### ISSUE THREAD

**Issue by Hollicsh** [ketho-wow/KethoInstanceTimer#5]
364x KethoInstanceTimer/Broker.lua:51: attempt to index field 'pvp' (a nil value)
[string "@KethoInstanceTimer/Broker.lua"]:51: in function <KethoInstanceTimer/Broker.lua:50>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'pvp' (a nil value)"
S = <table> {
 L = <table> {
 }
}
dataobject = <table> {
}
KIT = nil

**Comment by Ketho** [comment]
I can't look at it until next week sorry

**Comment by Hollicsh** [comment]
OK. Need update all libraries, they are very outdated (last upd since 2022 year).

https://github.com/ketho-wow/KethoInstanceTimer/commit/337a8adfc88eda822470ba1588770b8d6d417982 - work fine.

**Comment by Ketho** [comment]
Thanks again for the PR, I pushed a v3.2.0 release
